---
- name: Validating if the package is installed or not
  apt:
    name: "{{item}}"
  with_items:
    - python3
    - python3-pip
    - net-tools

- name: Install docker
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - linode-cli

- name: Run docker containers
  docker_container:
    name: mhddos_proxy
    # auto_remove: no
    image: ghcr.io/porthole-ascend-cinnamon/mhddos_proxy
    command: "{{ ['-t', 1000 ] + tickler_targets }}"


